GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons/ 
content-type: application/json

{
    "name": "Thomas",
    "number": "444-555-5555"
}

###
DELETE http://localhost:3001/api/persons/fsfs

###
PUT  http://localhost:3001/api/persons/61522ac3cf29e535787fe9fd 
content-type: application/json

{
    "number": "444-555-5555"
}